version: "3"
services:
 frontend-clinet:
   container_name: clinet-container
   build:
    context: ./frontend
    dockerfile: Dockerfile
   image: clinet-image
   ports:
   - "5173:5173"
   networks:
   - mynetwork

networks:
 mynetwork:
  driver: bridge